#pragma once

#ifndef HELLO_WORD_KEYBOARD_FW_HW_CORE_H
#define HELLO_WORD_KEYBOARD_FW_HW_CORE_H

#include <cstdint>
#include "hw_config.h"
#include "hw_types.h"

#ifndef RGB_MATRIX_ENABLE
#undef RGB_MATRIX_KEYREACTIVE_ENABLED
#undef RGB_MATRIX_FRAMEBUFFER_EFFECTS
#endif

#ifndef LED_NUMS
#define LED_NUMS NO_LED
#endif
#ifndef LED_CAPS
#define LED_CAPS NO_LED
#endif
#ifndef LED_SCROLL
#define LED_SCROLL NO_LED
#endif
#ifndef LED_COMPOSE
#define LED_COMPOSE NO_LED
#endif
#ifndef LED_KANA
#define LED_KANA NO_LED
#endif

#if defined(EEPROM_CONFIG)
  #ifndef EEPROM_CONFIG_TIME
  #define EEPROM_CONFIG_TIME 600 * 1000
  #endif
#else
#undef EEPROM_CONFIG_TIME
#endif

#if defined(RGB_MATRIX_KEYREACTIVE_ENABLED)

#if defined(RGB_MATRIX_KEYPRESSES)
#undef RGB_MATRIX_KEYRELEASE
#elif defined(RGB_MATRIX_KEYRELEASE)
#undef RGB_MATRIX_KEYPRESSES
#else
#define RGB_MATRIX_KEYRELEASE
#endif

#else
#undef RGB_MATRIX_KEYPRESSES
#undef RGB_MATRIX_KEYRELEASE
#endif

#if defined(RGB_MATRIX_ENABLE)
  #ifndef RGB_MATRIX_BRIGHTNESS_STEP
  #define RGB_MATRIX_BRIGHTNESS_STEP 32
  #endif

  #ifndef RGB_MATRIX_MAXIMUM_BRIGHTNESS
  #define RGB_MATRIX_MAXIMUM_BRIGHTNESS UINT8_MAX - RGB_MATRIX_BRIGHTNESS_STEP
  #endif
  
  #ifndef RGB_MATRIX_DEFAULT_HUE
  #define RGB_MATRIX_DEFAULT_HUE 0
  #endif

  #ifndef RGB_MATRIX_DEFAULT_SAT
  #define RGB_MATRIX_DEFAULT_SAT UINT8_MAX
  #endif

  #ifndef RGB_MATRIX_DEFAULT_VAL
  #define RGB_MATRIX_DEFAULT_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS
  #endif

  #ifndef RGB_MATRIX_DEFAULT_SPD
  #define RGB_MATRIX_DEFAULT_SPD UINT8_MAX / 2
  #endif

  #ifndef RGB_MATRIX_CENTER
  #define RGB_MATRIX_CENTER {112, 32}
  #endif

  #ifndef RGB_MATRIX_FRAMEBUFFER_EFFECTS
  #define RGB_MATRIX_FRAMEBUFFER_EFFECTS
  #endif
#else
#undef RGB_MATRIX_BRIGHTNESS_STEP
#undef RGB_MATRIX_MAXIMUM_BRIGHTNESS
#undef RGB_MATRIX_DEFAULT_HUE
#undef RGB_MATRIX_DEFAULT_SAT
#undef RGB_MATRIX_DEFAULT_VAL
#undef RGB_MATRIX_DEFAULT_SPD
#undef RGB_MATRIX_CENTER
#undef RGB_MATRIX_FRAMEBUFFER_EFFECTS
#endif

#ifndef RGB_MATRIX_ENABLE
#undef ENABLE_RGB_MATRIX_ALPHAS_MODS
#undef ENABLE_RGB_MATRIX_BREATHING
#undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#undef ENABLE_RGB_MATRIX_BAND_SAT
#undef ENABLE_RGB_MATRIX_BAND_VAL
#undef ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#undef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#undef ENABLE_RGB_MATRIX_CYCLE_ALL
#undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#undef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#undef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#undef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#undef ENABLE_RGB_MATRIX_DIGITAL_RAIN
#undef ENABLE_RGB_MATRIX_DUAL_BEACON
#undef ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#undef ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#undef ENABLE_RGB_MATRIX_HUE_BREATHING
#undef ENABLE_RGB_MATRIX_HUE_PENDULUM
#undef ENABLE_RGB_MATRIX_HUE_WAVE
#undef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#undef ENABLE_RGB_MATRIX_PIXEL_FLOW
#undef ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#undef ENABLE_RGB_MATRIX_PIXEL_RAIN
#undef ENABLE_RGB_MATRIX_RAINBOW_BEACON
#undef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#undef ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#undef ENABLE_RGB_MATRIX_RAINDROPS
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#undef ENABLE_RGB_MATRIX_SPLASH
#undef ENABLE_RGB_MATRIX_MULTISPLASH
#undef ENABLE_RGB_MATRIX_SOLID_SPLASH
#undef ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
#undef ENABLE_RGB_MATRIX_TYPING_HEATMAP
#endif

#include "keycodes.h"
#include "hw_keyboard.h"
#include "hw_led.h"

#ifdef RGB_MATRIX_ENABLE
#include "rgb_matrix_types.h"
#include "rgb_matrix.h"
#endif

#include "hw_layout.h"

const int16_t combCodeMap[] = {
    KB_SU_MY_COMPUTER, KB_SU_DIS_BRIGHTNESS_INC, KB_SU_DIS_BRIGHTNESS_DEC,
     KB_SU_MEDIA_SELECT, KB_SU_SCAN_PREV_TRACK, KB_SU_SCAN_NEXT_TRACK,
     KB_SU_PLAY_PAUSE, KB_SU_STOP, KB_SU_VOLUME_INC, KB_SU_VOLUME_DEC,
     KB_SU_MUTE, KB_SU_CALCULATOR, KB_KS_RGBMODE, KB_KS_BRIGHT_INC,
     KB_KS_BRIGHT_DEC, KB_KS_LAYER, KB_KS_CFG_SV, KB_KS_HUE_LOOP, 
};

#endif