#pragma once

#ifndef HELLO_WORD_KEYBOARD_FW_HW_KEYCODES_H
#define HELLO_WORD_KEYBOARD_FW_HW_KEYCODES_H

#include <cstdint>

enum keycode_ranges
{
	/*------------------------- HID report data -------------------------*/
	LEFT_CTRL = -8, LEFT_SHIFT = -7, LEFT_ALT = -6, LEFT_GUI = -5, 
	RIGHT_CTRL = -4, RIGHT_SHIFT = -3, RIGHT_ALT = -2, RIGHT_GUI = -1, 

	RESERVED = 0, ERROR_ROLL_OVER, POST_FAIL, ERROR_UNDEFINED, 
	A, B, C, D, E, F, G, H, I, J, K, L, M, 
	N, O, P, Q, R, S, T, U, V, W, X, Y, Z, 
	NUM_1/*1!*/, NUM_2/*2@*/, NUM_3/*3#*/, NUM_4/*4$*/, NUM_5/*5%*/, 
	NUM_6/*6^*/, NUM_7/*7&*/, NUM_8/*8**/, NUM_9/*9(*/, NUM_0/*0)*/, 
	ENTER, ESC, BACKSPACE, TAB, SPACE, 
	MINUS/*-_*/, EQUAL/*=+*/, LEFT_U_BRACE/*[{*/, RIGHT_U_BRACE/*]}*/, 
	BACKSLASH/*\|*/, NONE_US/**/, SEMI_COLON/*;:*/, QUOTE/*'"*/, 
	GRAVE_ACCENT/*`~*/, COMMA/*, <*/, PERIOD/*.>*/, SLASH/*/?*/, 
	CAP_LOCK, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, 
	PRINT, SCROLL_LOCK, PAUSE, INSERT, HOME, PAGE_UP, DELETE, END, PAGE_DOWN, 
	RIGHT_ARROW, LEFT_ARROW, DOWN_ARROW, UP_ARROW, PAD_NUM_LOCK, 
	PAD_SLASH, PAD_ASTERISK, PAD_MINUS, PAD_PLUS, PAD_ENTER, 
	PAD_NUM_1, PAD_NUM_2, PAD_NUM_3, PAD_NUM_4, PAD_NUM_5, 
	PAD_NUM_6, PAD_NUM_7, PAD_NUM_8, PAD_NUM_9, PAD_NUM_0, 
	PAD_PERIOD ,  NONUS_BACKSLASH, APPLICATION, POWER, PAD_EQUAL, 
	F13, F14, F15, F16, F17, F18, F19, F20, F21, F22, F23, F24,  EXECUTE, 
	HELP, MENU, SELECT, STOP, AGAIN, UNDO, CUT, COPY, PASTE, FIND, MUTE, VOLUME_UP, VOLUME_DOWN, 
  KB_KS_RGBMODE, KB_KS_BRIGHT_INC, KB_KS_BRIGHT_DEC, KB_KS_FILTER_INC, KB_KS_FILTER_DEC, KB_KS_LAYER, 
  KB_SU_DIS_BRIGHTNESS_INC, KB_SU_DIS_BRIGHTNESS_DEC, KB_SU_SCAN_NEXT_TRACK, KB_SU_SCAN_PREV_TRACK, 
  KB_SU_STOP, KB_SU_PLAY_PAUSE, KB_SU_MUTE, KB_SU_BASS_BOSST, 
  KB_SU_LOUDNESS, KB_SU_VOLUME_INC, KB_SU_VOLUME_DEC, KB_SU_BASS_INC, 
  KB_SU_BASS_DEC, KB_SU_TREBLE_UP, KB_SU_TREBLE_DOWN, KB_SU_MEDIA_SELECT, 
  KB_SU_MAIL, KB_SU_CALCULATOR, KB_SU_MY_COMPUTER, 
  KB_SU_WWW_SEARCH, KB_SU_WWW_HOME, KB_SU_WWW_BACK, KB_SU_WWW_FORWARD, 
  WKB_SU_WW_STOP, KB_SU_WWW_REFRESH, KB_SU_WWW_FAVORITES, KB_KS_CFG_SV, KB_KS_HUE_LOOP, 
	FN = 1000
	/*------------------------- HID report data -------------------------*/
};

enum consumer_ranges
{
	/*------------------------- HID Consumer report data -------------------------*/
	DISPLAY_BRIGHTNESS_INC = 0x006F, DISPLAY_BRIGHTNESS_DEC = 0x0070, SCAN_NEXT_TRACK = 0x00B5, SCAN_PREV_TRACK = 0x00B6,
	SU_STOP = 0x00B7, PLAY_PAUSE = 0x00CD, SU_MUTE = 0x00E2, BASS_BOOST = 0x00E5,
	LOUDNESS = 0x00E7, SU_VOLUME_INC = 0x00E9, SU_VOLUME_DEC = 0x00EA, BASS_INC = 0x0152,
	BASS_DEC = 0x0153, TREBLE_UP = 0x0154, TREBLE_DOWN = 0x0155, MEDIA_SELECT = 0x0183,
	MAIL = 0x018A, CALCULATOR = 0x0192, MY_COMPUTER = 0x0194,
	WWW_SEARCH = 0x0221, WWW_HOME = 0x0223, WWW_BACK = 0x0224, WWW_FORWARD = 0x0225,
	WWW_STOP = 0x0226, WWW_REFRESH = 0x0227, WWW_FAVORITES = 0x022A,

	/*------------------------- HID Custom data don't send -------------------------*/
	KEYSET_LIGHTMODE = 0x6000,
	KEYSET_BRIGHTNESS_INC = 0x6101,
	KEYSET_BRIGHTNESS_DEC = 0x6100,
	KEYSET_FILTER_LEVEL_INC = 0x6201,
	KEYSET_FILTER_LEVEL_DEC = 0x6200,
	KEYSET_LAYOUT_WIN_MAC = 0x6300,
	KEYSET_CONFIG_SAVE = 0x6400,
  KEYSET_HSV_HUE_LOOP = 0x6500,
	/*------------------------- HID Consumer report data -------------------------*/
};

#endif